add variable to disallow hvst import

diff --git a/validation/pipeline/tfp/Jenkinsfile.harvester.e2e b/validation/pipeline/tfp/Jenkinsfile.harvester.e2e
--- a/validation/pipeline/tfp/Jenkinsfile.harvester.e2e
+++ b/validation/pipeline/tfp/Jenkinsfile.harvester.e2e
@@ -257,7 +257,7 @@ node("harvester-vpn-1") {
                             returnStdout: true
                         ).trim()
                         commitIDTest = sh(
-                            script: "cd infra-repo && git rev-parse --short HEAD",
+                            script: "cd test-repo && git rev-parse --short HEAD",
                             returnStdout: true
                         ).trim()
 
@@ -367,39 +367,43 @@ node("harvester-vpn-1") {
                         
                     }
                     stage('Connect Rancher -> Harvester') {
-                        try {
-                            // this test also writes harvesterCloudCredentials to the config
-                            sh( script: """
-                        docker run -v ${validationVolume}:/root --name hvst${golangTestContainer} -t  ${imageName}${TOFU_VERSION}${HARVESTER_PROVIDER_VERSION}${RANCHER2_PROVIDER_VERSION}-${commitIDTest}:${commitIDInfra} sh -c "cp "\$CATTLE_TEST_CONFIG" . && export CATTLE_TEST_CONFIG="\$CATTLE_TEST_CONFIG" && /root/go/bin/gotestsum --format standard-verbose --packages=${golangHvstDir} --junitfile ${testResultsOut} -- -tags=${TAGS} ${hvstTestCase} -timeout=${timeout} -v "
-                        """, returnStatus: true)
-                        } catch (err) {
-                            echo "${err} Unable to connect harvester to new rancher setup. Aborting"
-                            sh "docker stop hvst${golangTestContainer} || true; docker rm hvst${golangTestContainer}"
-                            error err
+                        if (env.CONNECT_HARVESTER_AND_RANCHER == "true") {
+                            try {
+                                // this test also writes harvesterCloudCredentials to the config
+                                sh( script: """
+                            docker run -v ${validationVolume}:/root --name hvst${golangTestContainer} -t  ${imageName}${TOFU_VERSION}${HARVESTER_PROVIDER_VERSION}${RANCHER2_PROVIDER_VERSION}-${commitIDTest}:${commitIDInfra} sh -c "cp "\$CATTLE_TEST_CONFIG" . && export CATTLE_TEST_CONFIG="\$CATTLE_TEST_CONFIG" && /root/go/bin/gotestsum --format standard-verbose --packages=${golangHvstDir} --junitfile ${testResultsOut} -- -tags=${TAGS} ${hvstTestCase} -timeout=${timeout} -v "
+                            """, returnStatus: true)
+                            } catch (err) {
+                                echo "${err} Unable to connect harvester to new rancher setup. Aborting"
+                                sh "docker stop hvst${golangTestContainer} || true; docker rm hvst${golangTestContainer}"
+                                error err
+                            }
+                            sh "docker cp hvst${golangTestContainer}:\$CATTLE_TEST_CONFIG ${filename}"
                         }
-                        sh "docker cp hvst${golangTestContainer}:\$CATTLE_TEST_CONFIG ${filename}"
                     }
                     stage('Create Downstream Cluster for Testing') {
-                        dir("infra-repo") {
-                                def IMPORTED_HVST_KUBECONFIG = sh (
-                                    script: "yq -r '.harvesterCredentials.kubeconfigContent' ../${filename}",
-                                    returnStdout: true
-                                ).trim()
-                                def IMPORTED_HVST_V3_ID = sh (
-                                    script: "yq '.harvesterCredentials.clusterId' ../${filename}",
-                                    returnStdout: true
-                                ).trim()
-                                def tfvars_filepath = "cluster.tfvars"
-                                writeFile file: tfvars_filepath, text: DOWNSTREAM_CLUSTER_CONFIG
-                                sh """
-                                sed -i -E \
-                                    -e 's|kubernetes_version = ".*"|kubernetes_version = "${RANCHER_KUBERNETES_VERSION}"|' \
-                                    -e 's|harvester_cluster_v1_id = ".*"|harvester_cluster_v1_id = "${IMPORTED_HVST_V3_ID}"|' \
-                                    ${tfvars_filepath}
-                                """
+                        if (env.CONNECT_HARVESTER_AND_RANCHER == "true") {
 
-                                // multiline is different
-                                sh """
+                            dir("infra-repo") {
+                                    def IMPORTED_HVST_KUBECONFIG = sh (
+                                        script: "yq -r '.harvesterCredentials.kubeconfigContent' ../${filename}",
+                                        returnStdout: true
+                                    ).trim()
+                                    def IMPORTED_HVST_V3_ID = sh (
+                                        script: "yq '.harvesterCredentials.clusterId' ../${filename}",
+                                        returnStdout: true
+                                    ).trim()
+                                    def tfvars_filepath = "cluster.tfvars"
+                                    writeFile file: tfvars_filepath, text: DOWNSTREAM_CLUSTER_CONFIG
+                                    sh """
+                                    sed -i -E \
+                                        -e 's|kubernetes_version = ".*"|kubernetes_version = "${RANCHER_KUBERNETES_VERSION}"|' \
+                                        -e 's|harvester_cluster_v1_id = ".*"|harvester_cluster_v1_id = "${IMPORTED_HVST_V3_ID}"|' \
+                                        ${tfvars_filepath}
+                                    """
+
+                                    // multiline is different
+                                    sh """
 # Remove existing block
 echo "${IMPORTED_HVST_KUBECONFIG}"
 sed -i '/harvester_kubeconfig_content = <<EOF/,/EOF/d' "${tfvars_filepath}"
@@ -413,53 +417,59 @@ EOF
 echo "}\\n" >> "${tfvars_filepath}"
 
 # echo "\\nEOF\\n}\\n" >> "${tfvars_filepath}"
-                            """
+                                """
 
-                                // run the test with tofu
-                                sh """
-                            
-                            cat ${tfvars_filepath}
-                            docker cp ${tfvars_filepath} hvst${golangTestContainer}:/root/go/src/github.com/rancher/qa-infra-automation/tofu/rancher/cluster/
-                            docker stop hvst${golangTestContainer} || true; docker rm hvst${golangTestContainer}
+                                    // run the test with tofu
+                                    sh """
+                                
+                                cat ${tfvars_filepath}
+                                docker cp ${tfvars_filepath} hvst${golangTestContainer}:/root/go/src/github.com/rancher/qa-infra-automation/tofu/rancher/cluster/
+                                docker stop hvst${golangTestContainer} || true; docker rm hvst${golangTestContainer}
 
-                            docker run -v ${validationVolume}:/root --name ${testContainer}-ds -t ${imageName}${TOFU_VERSION}${HARVESTER_PROVIDER_VERSION}${RANCHER2_PROVIDER_VERSION}-${commitIDTest}:${commitIDInfra} sh -c '
-                            . /root/playbook.env
-                            . ./validation/pipeline/scripts/register_downstream_cluster.sh
-                            '
-                            docker stop ${testContainer}-ds || true; docker rm ${testContainer}-ds
-                            sleep 90
-                            """
+                                docker run -v ${validationVolume}:/root --name ${testContainer}-ds -t ${imageName}${TOFU_VERSION}${HARVESTER_PROVIDER_VERSION}${RANCHER2_PROVIDER_VERSION}-${commitIDTest}:${commitIDInfra} sh -c '
+                                . /root/playbook.env
+                                . ./validation/pipeline/scripts/register_downstream_cluster.sh
+                                '
+                                docker stop ${testContainer}-ds || true; docker rm ${testContainer}-ds
+                                sleep 90
+                                """
+                            }
                         }
                     }
                     stage('Run Validation Tests') {
-                        
-                        sh """
-                        docker run -v ${validationVolume}:/root --name ${golangTestContainer} -t ${imageName}${TOFU_VERSION}${HARVESTER_PROVIDER_VERSION}${RANCHER2_PROVIDER_VERSION}-${commitIDTest}:${commitIDInfra} sh -c "cp \$CATTLE_TEST_CONFIG . && export CATTLE_TEST_CONFIG=/root/go/src/github.com/rancher/tests/config.yml && /root/go/bin/gotestsum --format standard-verbose --packages=${golangTestDir} --junitfile ${testResultsOut} -- -tags=${TAGS} ${GO_TEST_CASE} -timeout=${timeout} -v ;"
-                        """
-                        
-                        sh "docker cp ${golangTestContainer}:/root/go/src/github.com/rancher/tests/config.yml final_config.yml"
-                        
-                        def r_host = sh (
-                            script: "yq '.rancher.host' final_config.yml",
-                            returnStdout: true
-                        ).trim()
+                        if (env.CONNECT_HARVESTER_AND_RANCHER == "true") {
+                            try {
+                                sh """
+                                docker run -v ${validationVolume}:/root --name ${golangTestContainer} -t ${imageName}${TOFU_VERSION}${HARVESTER_PROVIDER_VERSION}${RANCHER2_PROVIDER_VERSION}-${commitIDTest}:${commitIDInfra} sh -c "cp \$CATTLE_TEST_CONFIG . && export CATTLE_TEST_CONFIG=/root/go/src/github.com/rancher/tests/config.yml && /root/go/bin/gotestsum --format standard-verbose --packages=${golangTestDir} --junitfile ${testResultsOut} -- -tags=${TAGS} ${GO_TEST_CASE} -timeout=${timeout} -v ;"
+                                """
+                            } catch (err) {
+                                echo "${err} Test had failures.."
+                            }
+                            
+                            sh "docker cp ${golangTestContainer}:/root/go/src/github.com/rancher/tests/config.yml final_config.yml"
+                            
+                            def r_host = sh (
+                                script: "yq '.rancher.host' final_config.yml",
+                                returnStdout: true
+                            ).trim()
 
-                        def r_pass = sh (
-                            script: "yq '.rancher.adminPassword' final_config.yml",
-                            returnStdout: true
-                        ).trim()
+                            def r_pass = sh (
+                                script: "yq '.rancher.adminPassword' final_config.yml",
+                                returnStdout: true
+                            ).trim()
 
-                        def h_host = sh (
-                            script: "yq '.harvester.host' final_config.yml",
-                            returnStdout: true
-                        ).trim()
+                            def h_host = sh (
+                                script: "yq '.harvester.host' final_config.yml",
+                                returnStdout: true
+                            ).trim()
 
-                        currentBuild.description = "https://${r_host}\n${r_pass}\nhttps://${h_host}\n"
+                            currentBuild.description = "https://${r_host}\\n${r_pass}\\nhttps://${h_host}\\n"
 
-                        sh """
-                        docker stop ${golangTestContainer} || true
-                        docker rm ${golangTestContainer} || true                        
-                        """
+                            sh """
+                            docker stop ${golangTestContainer} || true
+                            docker rm ${golangTestContainer} || true                        
+                            """
+                        }
                     }
                     stage('Cleanup terraform resources') {
                         if (env.CLEANUP == "true") {
