Update template_test.go to read template-chart.yaml instead of forked GitHub repo (#823)

diff --git a/.github/actions/run-hostbusters-provisioning/action.yaml b/.github/actions/run-hostbusters-provisioning/action.yaml
--- a/.github/actions/run-hostbusters-provisioning/action.yaml
+++ b/.github/actions/run-hostbusters-provisioning/action.yaml
@@ -30,46 +30,16 @@ runs:
       run: |
         set +e
 
-        gotestsum --format standard-verbose \
-          --packages=github.com/rancher/tests/validation/provisioning/... \
-          --junitfile results.xml \
-          --jsonfile results_provisioning.json \
-          -- -parallel 4 -timeout=3h -tags=${{ inputs.tags }} -v
-
-        provisioning_exit=$?
-        echo "provisioning_exit=$provisioning_exit" >> "$GITHUB_ENV"
-        cp results_provisioning.json results.json
-  
-        if [[ "${{ inputs.reporting }}" == "true" ]]; then
-          ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
-          ./validation/reporter
-        fi
-
         if [[ "${{ inputs.run_template }}" == "true" ]]; then
           gotestsum --format standard-verbose \
-            --packages=github.com/rancher/tests/validation/provisioning/k3s \
+            --packages=github.com/rancher/tests/validation/provisioning/... \
             --junitfile results.xml \
-            --jsonfile results_k3s_template.json \
+            --jsonfile results_template.json \
             -- -timeout=3h -tags=template -v
 
-          k3s_template_exit=$?
-          echo "k3s_template_exit=$k3s_template_exit" >> "$GITHUB_ENV"
-          cp results_k3s_template.json results.json
-    
-          if [[ "${{ inputs.reporting }}" == "true" ]]; then
-            ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
-            ./validation/reporter
-          fi
-
-          gotestsum --format standard-verbose \
-            --packages=github.com/rancher/tests/validation/provisioning/rke2 \
-            --junitfile results.xml \
-            --jsonfile results_rke2_template.json \
-            -- -timeout=3h -tags=template -v
-
-          rke2_template_exit=$?
-          echo "rke2_template_exit=$rke2_template_exit" >> "$GITHUB_ENV"
-          cp results_rke2_template.json results.json
+          template_exit=$?
+          echo "template_exit=$template_exit" >> "$GITHUB_ENV"
+          cp results_template.json results.json
     
           if [[ "${{ inputs.reporting }}" == "true" ]]; then
             ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
@@ -109,26 +79,30 @@ runs:
           fi
         fi
 
+        gotestsum --format standard-verbose \
+          --packages=github.com/rancher/tests/validation/provisioning/... \
+          --junitfile results.xml \
+          --jsonfile results_provisioning.json \
+          -- -parallel 4 -timeout=3h -tags=${{ inputs.tags }} -v
+
+        provisioning_exit=$?
+        echo "provisioning_exit=$provisioning_exit" >> "$GITHUB_ENV"
+        cp results_provisioning.json results.json
+  
+        if [[ "${{ inputs.reporting }}" == "true" ]]; then
+          ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
+          ./validation/reporter
+        fi
+
     - name: Show failed tests
       shell: bash
       run: |
         failed=0
 
-        if [ "${provisioning_exit:-}" != "" ] && [ "$provisioning_exit" -ne 0 ]; then
-          echo "Failed Provisioning tests:"
-          jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results_provisioning.json
-          failed=1
-        fi
-
         if [[ "${{ inputs.run_template }}" == "true" ]]; then
-          if [ "${k3s_template_exit:-}" != "" ] && [ "$k3s_template_exit" -ne 0 ]; then
-            echo "Failed K3S Template tests:"
-            jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results_k3s_template.json
-            failed=1
-          fi
-          if [ "${rke2_template_exit:-}" != "" ] && [ "$rke2_template_exit" -ne 0 ]; then
-            echo "Failed RKE2 Template tests:"
-            jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results_rke2_template.json
+          if [ "${template_exit:-}" != "" ] && [ "$template_exit" -ne 0 ]; then
+            echo "Failed Template tests:"
+            jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results_template.json
             failed=1
           fi
         fi
@@ -139,11 +113,18 @@ runs:
             jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results_k3s_ace.json
             failed=1
           fi
+
           if [ "${rke2_ace_exit:-}" != "" ] && [ "$rke2_ace_exit" -ne 0 ]; then
             echo "Failed RKE2 ACE tests:"
             jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results_rke2_ace.json
             failed=1
           fi
+        fi
+
+        if [ "${provisioning_exit:-}" != "" ] && [ "$provisioning_exit" -ne 0 ]; then
+          echo "Failed Provisioning tests:"
+          jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results_provisioning.json
+          failed=1
         fi
 
         if [ "$failed" -eq 1 ]; then
