fix: streamline S3 download command for cluster.tfvars with improved formatting

diff --git a/validation/pipeline/Jenkinsfile.destroy.airgap.rke2 b/validation/pipeline/Jenkinsfile.destroy.airgap.rke2
--- a/validation/pipeline/Jenkinsfile.destroy.airgap.rke2
+++ b/validation/pipeline/Jenkinsfile.destroy.airgap.rke2
@@ -538,20 +538,15 @@ mkdir -p tofu/aws/modules/airgap
 
 # cspell:ignore tfvars
 echo 'Downloading cluster.tfvars from S3...'
-aws s3 cp \
-    s3://"${env.S3_BUCKET_NAME}"/env:/"${env.TF_WORKSPACE}"/config/"${env.TERRAFORM_VARS_FILENAME}" \
-    tofu/aws/modules/airgap/"${env.TERRAFORM_VARS_FILENAME}" \
-    --region "${env.S3_REGION}"
+aws s3 cp s3://${env.S3_BUCKET_NAME}/env:/${env.TF_WORKSPACE}/config/${env.TERRAFORM_VARS_FILENAME} tofu/aws/modules/airgap/${env.TERRAFORM_VARS_FILENAME} --region ${env.S3_REGION}
 
 if [ \$? -eq 0 ]; then
     echo 'SUCCESS: cluster.tfvars downloaded from S3'
-    ls -la tofu/aws/modules/airgap/"${env.TERRAFORM_VARS_FILENAME}"
+    ls -la tofu/aws/modules/airgap/${env.TERRAFORM_VARS_FILENAME}
 else
     echo 'ERROR: Failed to download cluster.tfvars from S3'
     echo 'Available files in S3 config directory:'
-    aws s3 ls \
-        s3://"${env.S3_BUCKET_NAME}"/env:/"${env.TF_WORKSPACE}"/config/" \
-        --region "${env.S3_REGION}" || echo 'Failed to list S3 contents'
+    aws s3 ls s3://${env.S3_BUCKET_NAME}/env:/${env.TF_WORKSPACE}/config/ --region ${env.S3_REGION} || echo 'Failed to list S3 contents'
     exit 1
 fi
 echo 'Configuration files downloaded successfully'
