Add infrastructure initialization step during cleanup for timeout and deployment failures

diff --git a/validation/pipeline/Jenkinsfile.airgap.rke2.improved b/validation/pipeline/Jenkinsfile.airgap.rke2.improved
--- a/validation/pipeline/Jenkinsfile.airgap.rke2.improved
+++ b/validation/pipeline/Jenkinsfile.airgap.rke2.improved
@@ -264,6 +264,8 @@ cd ${env.QA_INFRA_WORK_PATH}
 export TF_WORKSPACE="${env.TF_WORKSPACE}"
 
 echo 'Performing infrastructure cleanup due to timeout...'
+tofu -chdir=tofu/aws/modules/airgap init -input=false -upgrade || echo 'Init failed during cleanup - manual intervention required'
+
 tofu -chdir=tofu/aws/modules/airgap destroy -auto-approve -var-file="${env.TERRAFORM_VARS_FILENAME}" || echo 'Destroy command failed - manual cleanup may be required'
 echo 'Cleanup attempt completed'
                                     """
@@ -290,6 +292,8 @@ cd ${env.QA_INFRA_WORK_PATH}
 export TF_WORKSPACE="${env.TF_WORKSPACE}"
 
 echo 'Performing infrastructure cleanup due to deployment failure...'
+tofu -chdir=tofu/aws/modules/airgap init -input=false -upgrade || echo 'Init failed during cleanup - manual intervention required'
+
 tofu -chdir=tofu/aws/modules/airgap destroy -auto-approve -var-file="${env.TERRAFORM_VARS_FILENAME}" || echo 'Destroy command failed - manual cleanup may be required'
 echo 'Cleanup attempt completed'
                                     """
@@ -1003,6 +1007,8 @@ fi
 
 export TF_WORKSPACE="${env.TF_WORKSPACE}"
 echo "Workspace management completed: \$TF_WORKSPACE"
+
+tofu -chdir=tofu/aws/modules/airgap init -input=false -upgrade
     """
 
     executeScriptInContainer(workspaceScript)
