feat: add S3 upload of terraform config files in Jenkins pipeline

diff --git a/validation/pipeline/Jenkinsfile.airgap.rke2.improved b/validation/pipeline/Jenkinsfile.airgap.rke2.improved
--- a/validation/pipeline/Jenkinsfile.airgap.rke2.improved
+++ b/validation/pipeline/Jenkinsfile.airgap.rke2.improved
@@ -1136,6 +1136,33 @@ fi
 echo 'Backing up terraform variables file for archival...'
 cp /root/go/src/github.com/rancher/qa-infra-automation/tofu/aws/modules/airgap/"${env.TERRAFORM_VARS_FILENAME}" /root/"${env.TERRAFORM_VARS_FILENAME}"
 
+echo 'Uploading configuration files to S3 bucket...'
+# Upload cluster.tfvars to S3
+echo 'Uploading cluster.tfvars to S3...'
+aws s3 cp /root/go/src/github.com/rancher/qa-infra-automation/tofu/aws/modules/airgap/"${env.TERRAFORM_VARS_FILENAME}" \
+    s3://"${env.S3_BUCKET_NAME}"/"${env.S3_KEY_PREFIX}"/config/"${env.TERRAFORM_VARS_FILENAME}" \
+    --region "${env.S3_REGION}"
+
+if [ \$? -eq 0 ]; then
+    echo 'SUCCESS: cluster.tfvars uploaded to S3'
+else
+    echo 'WARNING: Failed to upload cluster.tfvars to S3'
+fi
+
+# Upload backend.tfvars to S3
+echo 'Uploading backend.tfvars to S3...'
+aws s3 cp /root/go/src/github.com/rancher/qa-infra-automation/tofu/aws/modules/airgap/"${env.TERRAFORM_BACKEND_VARS_FILENAME}" \
+    s3://"${env.S3_BUCKET_NAME}"/"${env.S3_KEY_PREFIX}"/config/"${env.TERRAFORM_BACKEND_VARS_FILENAME}" \
+    --region "${env.S3_REGION}"
+
+if [ \$? -eq 0 ]; then
+    echo 'SUCCESS: backend.tfvars uploaded to S3'
+else
+    echo 'WARNING: Failed to upload backend.tfvars to S3'
+fi
+
+echo 'Configuration files upload completed'
+
 echo 'Generating outputs for downstream stages...'
 tofu -chdir=/root/go/src/github.com/rancher/qa-infra-automation/tofu/aws/modules/airgap output -json > /root/infrastructure-outputs.json
 
